Repository cerner/terra-dev-site, pull requests merged in 2018-02, with the labels that each got.

#18 Update Path Splitting
  CHANGELOG.md
  scripts/generate-component-config/build-component-config.js
Labels: bug

#25 Fix Extensions Error
  src/app/ApplicationHeader.jsx
Labels: bug

#24 Add Theming-plugin Jest Tests
  .eslintrc
  jestsetup.js
  package.json
  tests/theming-plugin/TestingComponent.scss
  tests/theming-plugin/theming-plugin-spec.test.jsx
Labels: testing, theming-plugin

#26 Minor Changes to generate-components-config Script
  CHANGELOG.md
  scripts/generate-component-config/generate-component-config.js
Labels: bug, enhancement, generate-component-config

#39 Rename to terra-dev-site
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTORS.md
  README.md
  package.json
  scripts/generate-component-config/generatedComponentConfig.template
  src/Index.jsx
  src/app/components/Components.jsx
  src/config/webpack.config.js
  tests/theming-plugin/theming-plugin-spec.test.jsx
Labels: Large

#41 Don't render nav links if there are not pages
  src/app/components/ComponentsUtils.js
Labels: bug
