Repository cerner/terra-dev-site, pull requests merged in 2018-03, with the labels that each got.

#43 Add ident key to Postcss-loader
  src/config/webpack.config.js
Labels: Small, configuration

#53 Clean up navigation.
  CHANGELOG.md
  src/app/components/ComponentsUtils.js
  src/app/configureApp.jsx
Labels: Small, enhancement

#51 Add search path extension
  CHANGELOG.md
  scripts/generate-component-config/build-component-config.js
  scripts/generate-component-config/generate-component-config.js
Labels: Large, generate-component-config

#52 Add generate-config bin
  CHANGELOG.md
  bin/generate-config.js
  package.json
Labels: Small, generate-component-config

#50 Configure App Tests
  package.json
  src/app/configureApp.jsx
  tests/app/MockComponent.jsx
  tests/app/configure-app-spec.test.jsx
  tests/app/mock-component-config-pages-tests.js
  tests/app/mock-component-config-pages.js
  tests/app/mock-component-config-tests.js
  tests/app/mock-component-config.js
Labels: Small, testing

#55 Remove console.
  tests/app/configure-app-spec.test.jsx
Labels: Small

#59 Create a placeholder site.
  .gitignore
  .travis.yml
  bin/generate-config.js
  componentConfig.js
  navigation.config.js
  package.json
  scripts/express/README.md
  scripts/express/app.js
  site.config.js
Labels: Small, testing

#61 Use terra application layout
  .eslintignore
  CHANGELOG.md
  index.js
  package.json
  site.config.js
  src/Index.jsx
  src/app/App.jsx
  src/app/ApplicationHeader.jsx
  src/app/ApplicationHeader.scss
  src/app/ApplicationMenu.jsx
  src/app/ApplicationToggle.jsx
  src/app/ApplicationToggle.scss
  src/app/ConfigureUtilities.jsx
  src/app/common/header-templates/Logo.jsx
  src/app/common/header-templates/Logo.scss
  src/app/common/header-templates/Utility.jsx
  src/app/common/header-templates/Utility.scss
  src/app/common/menu/MenuList.jsx
  src/app/common/menu/MenuList.scss
  src/app/common/menu/MenuToolbar.jsx
  src/app/common/menu/MenuToolbar.scss
  src/app/common/nav-tabs/NavTabs.jsx
  src/app/common/nav-tabs/NavTabs.scss
  src/app/common/toolbar/Toolbar.jsx
  src/app/common/toolbar/Toolbar.scss
  src/app/components/ComponentsMenu.jsx
  src/app/components/Extensions.jsx
  src/app/components/Extensions.scss
  src/app/components/GitHubLinkExtension.jsx
  src/app/components/RawRoute.jsx
  src/app/components/github-logo.png
  src/app/configureApp.js
  src/app/configureApp.jsx
  src/config/site.config.js
  tests/app/configure-app-spec.test.jsx
  themeable-variables.json
Labels: Large

#65 Whoops. Only Ignore the Repo Setup Not the Exported Config
  .npmignore
Labels: Small, bug
