Repository cerner/terra-dev-site, pull requests merged in 2018-06, with the labels that each got.

#78 Update the initial locale to be the `lang` attribute value
  CHANGELOG.md
  config/webpack/terra-dev-site.webpack.config.js
  scripts/generate-app-config/generateAppConfig.js
  src/Index.jsx
  src/app/App.jsx
  src/index.html
Labels: Small, testing

#85 Fixes to get Windows to start the server
  CHANGELOG.md
  CONTRIBUTORS.md
  scripts/generate-app-config/generatePagesConfig.js
  scripts/generate-app-config/generation-objects/ImportAggregator.js
Labels: bug

#90 Update to Use Toolkit v4
  CHANGELOG.md
  config/wdio/wdio.conf.js
  package-lock.json
  package.json
Labels: Major Version Bump
