Repository cerner/terra-dev-site, pull requests merged in 2019-05, with the labels that each got.

#152 Inject arbitrary html into head tag.
  CHANGELOG.md
  config/site/site.config.js
  config/webpack/terra-dev-site.webpack.config.js
  package-lock.json
  src/index.html
  src/terra-dev-site/doc/Configuration.b/navigation.config.b.doc.jsx
  src/terra-dev-site/doc/Configuration.b/navigation.config.b.doc.md
  src/terra-dev-site/doc/Configuration.b/navigation.config.md
  src/terra-dev-site/doc/Configuration.b/site.config.a.doc.jsx
  src/terra-dev-site/doc/Configuration.b/site.config.a.doc.md
  src/terra-dev-site/doc/Configuration.b/site.config.md
Labels: configuration, enhancement

#161 Script / Dev Dependency Clean Up
  package-lock.json
  package.json
  scripts/clean-modules/index.js
  scripts/release/README.md
  scripts/release/release.js
Labels: build-tools

#165 terra-dev-site v5
  .babelrc
  CHANGELOG.md
  babel.config.js
  config/site/site.config.js
  config/wdio/wdio.conf.js
  docker-compose.yml
  package-lock.json
  package.json
  src/Index.jsx
  src/terra-dev-site/doc/Configuration.b/navigation.config.b.doc.jsx
  src/terra-dev-site/doc/Configuration.b/site.config.a.doc.jsx
  src/terra-dev-site/doc/UpgradeGuides.c/v2.0.0.x.doc.md
  src/terra-dev-site/doc/UpgradeGuides.c/v3.0.0.w.doc.md
  src/terra-dev-site/doc/UpgradeGuides.c/v4.0.0.v.doc.md
  src/terra-dev-site/doc/UpgradeGuides.c/v5.0.0.x.doc.md
  src/theming-plugin.js
  tests/theming-plugin/TestingComponent.scss
  tests/theming-plugin/theming-plugin-spec.test.jsx
  themeable-variables.json
Labels: Major Version Bump
