Repository cerner/terra-dev-site, pull requests merged in 2019-08, with the labels that each got.

#183 Fix `TypeError: Cannot read property '0' of undefined` error
  CHANGELOG.md
  dev-site-config/navigation.config.js
  scripts/generate-app-config/generateContentConfig.js
  tests/wdio/__snapshots__/reference/en/chrome_huge/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/search-spec/search[selects_an_item].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/secondaryNavigation-spec/secondary_nav[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/singlePage-spec/home[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[config_changed].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[selects_config].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/utilities-spec/utilities[default].png
Labels: bug

#185 ESLint 6 Update
  CHANGELOG.md
  package.json
  scripts/generate-app-config/generateContentConfig.js
  scripts/generate-app-config/loadSiteConfig.js
  src/navigation/_CollapsingNavigationMenu.jsx
  src/navigation/_ComponentToolbar.jsx
  src/wrappers/_CodesplitWrapper.jsx
  src/wrappers/_MarkdownWrapper.jsx
Labels: dependency-update

#193 Locale override not applied
  CHANGELOG.md
  config/webpack/terra-dev-site.webpack.config.js
  package.json
  scripts/generate-app-config/generateAppConfig.js
  scripts/generate-app-config/generateSettingsConfig.js
  src/index.html
  tests/config/webpack/webpack.config.test.js
  tests/wdio/__snapshots__/reference/de/chrome_huge/raw-spec/raw_route[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/raw-spec/raw_route[hash_route].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/search-spec/search[selects_an_item].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/secondaryNavigation-spec/secondary_nav[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/singlePage-spec/home[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[config_changed].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[selects_config].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/raw-spec/raw_route[default].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/raw-spec/raw_route[hash_route].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/search-spec/search[selects_an_item].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/secondaryNavigation-spec/secondary_nav[default].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/singlePage-spec/home[default].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[config_changed].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[default].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[selects_config].png
  tests/wdio/i18n-spec.js
Labels: bug, bug-fix
