Repository cerner/terra-dev-site, pull requests merged in 2020-08, with the labels that each got.

#286 Secondary Navigation: Correct edge cases for no selection and duplicate labels.
  CHANGELOG.md
  src/navigation/_CollapsingNavigationMenu.jsx
  src/navigation/_CollapsingNavigationMenuItem.jsx
  tests/wdio/secondaryNavigation-spec.js
Labels: bug-fix

#289 Update propsTable to have unique selectors for styles
  CHANGELOG.md
  src/loader-components/PropsTable.module.scss
  tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md[css_syntax].png
  tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/marked-spec/md[diff_syntax].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/marked-spec/md[css_syntax].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/marked-spec/md[diff_syntax].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/marked-spec/md[css_syntax].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/marked-spec/md[diff_syntax].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md[css_syntax].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/marked-spec/md[diff_syntax].png
Labels: bug-fix

#290 [terra-dev-site] Expose status-overlay-provider
  CHANGELOG.md
  src/navigation/_SecondaryNavigationLayout.jsx
Labels: :package: terra-dev-site

#291 Add missing themeable variables
  .gitignore
  CHANGELOG.md
  src/loader-components/ExampleTemplate.module.scss
  src/loader-components/clinical-lowlight-theme/ExampleTemplate.module.scss
  src/loader-components/clinical-lowlight-theme/PropsTable.module.scss
  src/loader-components/orion-fusion-theme/ExampleTemplate.module.scss
  src/loader-components/orion-fusion-theme/PropsTable.module.scss
  src/marked/clinical-lowlight-theme/marked.module.scss
  src/marked/orion-fusion-theme/marked.module.scss
  src/mdx/clinical-lowlight-theme/MarkdownTags.module.scss
  src/mdx/orion-fusion-theme/MarkdownTags.module.scss
  src/navigation/SecondaryNavigationLayout.module.scss
  src/navigation/_SecondaryNavigationLayout.jsx
  src/navigation/clinical-lowlight-theme/CollapsingNavigationMenu.module.scss
  src/navigation/clinical-lowlight-theme/SecondaryNavigationLayout.module.scss
  src/navigation/orion-fusion-theme/CollapsingNavigationMenu.module.scss
  src/navigation/orion-fusion-theme/SecondaryNavigationLayout.module.scss
  src/terra-dev-site/component/ThemedComponent.module.scss
  src/terra-dev-site/component/clinical-lowlight-theme/ThemedComponent.module.scss
  src/terra-dev-site/component/orion-fusion-theme/ThemedComponent.module.scss
  src/terra-dev-site/component/terra-dev-site-test-theme/ThemedComponent.module.scss
  src/terra-dev-site/ff/ima folder/ima nother folder/Themed.module.scss
  src/wrappers/ContentLoaded.module.scss
  src/wrappers/clinical-lowlight-theme/ContentLoaded.module.scss
  src/wrappers/clinical-lowlight-theme/MarkdownWrapper.module.scss
  src/wrappers/orion-fusion-theme/ContentLoaded.module.scss
  src/wrappers/orion-fusion-theme/MarkdownWrapper.module.scss
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/loaders[Hides_css_tab].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/loaders[Hides_the_examples_code_again].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/loaders[Hides_the_examples_css_again].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/loaders[Reveals_the_examples_code].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/loaders[Reveals_the_examples_css].png
  tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/loaders-spec/loaders[example].png
  themes/clinical-lowlight-theme/clinical-lowlight-theme.scss
Labels: :star: UX Reviewed, bug-fix
