Repository cerner/terra-dev-site, pull requests merged in 2020-03, with the labels that each got.

#241 Fix codeblock loader to allow scss and css files.
  CHANGELOG.md
  config/webpack/loaderUtils/findSource.js
  config/webpack/loaders/devSiteCodeblock.js
  config/webpack/loaders/devSitePropsTable.js
  config/webpack/plugin/SetupPlugin.js
  src/terra-dev-site/test/loaders/codeblock-json.test.mdx
  src/terra-dev-site/test/loaders/codeblock-scss.test.mdx
  src/terra-dev-site/test/loaders/example.scss
  tests/wdio/__snapshots__/reference/de/chrome_huge/loaders-spec/loaders[scss_codeblock].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[default].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[opens_app_switcher].png
  tests/wdio/__snapshots__/reference/de/chrome_huge/utilities-spec/utilities[selects_config].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[opens_app_switcher].png
  tests/wdio/__snapshots__/reference/de/chrome_tiny/utilities-spec/utilities[selects_config].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/loaders-spec/loaders[scss_codeblock].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[opens_app_switcher].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/utilities-spec/utilities[selects_config].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/search-spec/search[default].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/search-spec/search[searches_the_site].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/utilities-spec/utilities[changes_config].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/utilities-spec/utilities[confirms_config].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/utilities-spec/utilities[opens_app_switcher].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/utilities-spec/utilities[selects_config].png
  tests/wdio/loaders-spec.js
Labels: bug-fix

#240 [terra-dev-site] Added clinical lowlight theme
  CHANGELOG.md
  dev-site-config/site.config.js
  terra-theme.config.js
  themes/clinical-lowlight-theme/clinical-lowlight-theme.scss
Labels: theming

#242 To improve build performance, do not aggregate the test theme.
  CHANGELOG.md
  dev-site-config/site.config.js
  dev-site-config/terra-dev-site-test-theme.scss
  terra-theme.config.js
Labels: tech-only
