Repository cerner/terra-dev-site, pull requests merged in 2020-04, with the labels that each got.

#244 Update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#245 Consolidate example component
  CHANGELOG.md
  dev-site-config/terra-dev-site-test-theme.scss
  package.json
  src/terra-dev-site/component/ThemedComponent.jsx
  src/terra-dev-site/component/ThemedComponent.module.scss
  src/terra-dev-site/component/clinical-lowlight-theme/ThemedComponent.module.scss
  src/terra-dev-site/component/orion-fusion-theme/ThemedComponent.module.scss
  src/terra-dev-site/component/terra-dev-site-test-theme/ThemedComponent.module.scss
  src/terra-dev-site/ff/ima folder/ima nother folder/themed.ff.jsx
  src/terra-dev-site/snt/Themed.module.scss
  src/terra-dev-site/snt/secondary-scroll-test/multiple-files/example1.snt.jsx
  src/terra-dev-site/snt/secondary-scroll-test/multiple-files/example2.snt.jsx
  src/terra-dev-site/snt/secondary-scroll-test/parent-folder/child-folder/example.snt.jsx
  src/terra-dev-site/snt/themed.a.snt.jsx
  src/terra-dev-site/spt/Themed.module.scss
  src/terra-dev-site/spt/themed.spt.jsx
  tests/wdio/__snapshots__/reference/de/chrome_huge/secondaryNavigation-spec/secondary_scroll_multiple_files[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/secondaryNavigation-spec/secondary_scroll_multiple_files[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/secondaryScroll-spec/secondary_scroll_multiple_directories[default].png
  tests/wdio/__snapshots__/reference/en/chrome_huge/secondaryScroll-spec/secondary_scroll_multiple_files[default].png
Labels: theming

#253 Fix lowlight theme problem
  CHANGELOG.md
  themes/clinical-lowlight-theme/clinical-lowlight-theme.scss
Labels: bug-fix

#258 Secondary navigation should not jump when item is visible on screen.
  CHANGELOG.md
  src/navigation/_CollapsingNavigationMenu.jsx
Labels: bug-fix
